version: '3.8'

services:
  inventory_db:
    image: postgres:alpine
    container_name: inventory_db
    ports:
      - "5432:5432"
    volumes: 
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ft_transcendence_network

  ft_transcendence:
    build: .
    container_name: ft_transcendence
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - inventory_db
    networks:
      - ft_transcendence_network
    restart: on-failure

networks:
  ft_transcendence_network:
    driver: bridge
