version: '3.8'

services:
  inventory_db:
    image: postgres:alpine
    container_name: inventory_db
    ports:
      - "5432:5432"
    volumes: 
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ft_transcendence_network
    restart: always

  ft_transcendence:
    build: .
    container_name: ft_transcendence
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - inventory_db
    networks:
      - ft_transcendence_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - ft_transcendence
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ft_transcendence_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - ft_transcendence_network
    restart: always

networks:
  ft_transcendence_network:
    driver: bridge
