services:
  auth:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3000:3000"
    env_file:
      - ./auth_service/.env
    depends_on:
      - postgres
    volumes:
      - "./auth_service:/app"
    networks:
      - ft_transcendence_network
    restart: always


  postgres:
    build:
      context: ./backend/postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - DB_PORT=${DB_PORT}
    container_name: postgres
    volumes: 
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - ft_transcendence_network
    restart: always

  backend:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
      args:
        - PYTHONUNBUFFERED=1
        - SECRET_KEY=${SECRET_KEY}
        - PRODUCTION=${PRODUCTION}
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/transcendence:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - auth
    networks:
      - ft_transcendence_network
    restart: always

  nginx:
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./auth_service/staticfiles:/app/staticfiles
    networks:
      - ft_transcendence_network
    restart: always

  adminer:
    build: 
      context: ./backend/adminer
      dockerfile: Dockerfile
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - ft_transcendence_network
    restart: always
  
  redis:
    build:
      context: ./backend/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - ft_transcendence_network
    restart: always

networks:
  ft_transcendence_network:
    driver: bridge

volumes:
  postgres: