# Generated by Django 4.2.3 on 2024-11-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_id', models.IntegerField(null=True)),
                ('player_a_id', models.IntegerField(null=True)),
                ('player_b_id', models.IntegerField(null=True)),
                ('player_c_id', models.IntegerField(null=True)),
                ('player_d_id', models.IntegerField(null=True)),
                ('winner_one', models.CharField(max_length=20, null=True)),
                ('winner_two', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='In progress', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
