# Generated by Django 4.2.3 on 2024-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_num_losses_user_num_wins_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(null=True),
        ),
    ]
