# Generated by Django 4.2.3 on 2024-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='us_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='us_2fa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
