# Generated by Django 4.2.3 on 2024-11-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_us_2fa_enabled_user_us_2fa_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='us_2fa_enabled',
            new_name='s_2fa_enabled',
        ),
    ]
