# Generated by Django 4.2.3 on 2024-11-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
