# Generated by Django 4.2.3 on 2024-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamescore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='status',
            field=models.CharField(default='In progress', max_length=20, null=True),
        ),
    ]
