# Generated by Django 4.2.16 on 2024-11-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='s_2fa_enabled',
            new_name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='us_2fa_secret',
        ),
    ]
