# Generated by Django 4.2.16 on 2024-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0002_rename_s_2fa_enabled_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=True),
        ),
    ]
