# Generated by Django 4.2.3 on 2024-11-09 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.IntegerField(null=True)),
                ('score_b', models.IntegerField(null=True)),
                ('status', models.CharField(default='In progress', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
