# Generated by Django 4.2.3 on 2024-11-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameboot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameBoot',
        ),
    ]
